#!/bin/bash
# Automatically builds and flashes Klipper firmware to all CAN devices.
# Devices: EBB36 (STM32G0B1) and Kraken (STM32H723)

set -e

KLIPPER_DIR=~/klipper
FLASH_SCRIPT=~/klippy-env/bin/python3 ~/katapult/scripts/flash_can.py

EBB36_UUID="9e1d04953b6c"
KRAKEN_UUID="49c000c1c373"

echo ">>> Stopping Klipper..."
systemctl stop klipper.service

# ─── Build & Flash EBB36 ────────────────────────────────────────────────────

echo ">>> Configuring firmware for EBB36 (STM32G0B1)..."
cat > "$KLIPPER_DIR/.config" <<'EOF'
CONFIG_LOW_LEVEL_OPTIONS=y
CONFIG_MACH_STM32=y
CONFIG_BOARD_DIRECTORY="stm32"
CONFIG_MCU="stm32g0b1xx"
CONFIG_CLOCK_FREQ=64000000
CONFIG_FLASH_SIZE=0x20000
CONFIG_FLASH_BOOT_ADDRESS=0x8000000
CONFIG_RAM_START=0x20000000
CONFIG_RAM_SIZE=0x24000
CONFIG_STACK_SIZE=512
CONFIG_FLASH_APPLICATION_ADDRESS=0x8002000
CONFIG_STM32_SELECT=y
CONFIG_MACH_STM32G0B1=y
CONFIG_MACH_STM32G0=y
CONFIG_MACH_STM32G0Bx=y
CONFIG_HAVE_STM32_USBFS=y
CONFIG_STM32_USB_DOUBLE_BUFFER_TX=y
CONFIG_HAVE_STM32_FDCANBUS=y
CONFIG_HAVE_STM32_USBCANBUS=y
CONFIG_STM32_DFU_ROM_ADDRESS=0
CONFIG_STM32_FLASH_START_2000=y
CONFIG_STM32_CLOCK_REF_8M=y
CONFIG_CLOCK_REF_FREQ=8000000
CONFIG_STM32F0_TRIM=16
CONFIG_STM32_MMENU_CANBUS_PB0_PB1=y
CONFIG_STM32_CANBUS_PB0_PB1=y
CONFIG_USB_VENDOR_ID=0x1d50
CONFIG_USB_DEVICE_ID=0x614e
CONFIG_USB_SERIAL_NUMBER="12345"
CONFIG_CANSERIAL=y
CONFIG_CANBUS=y
CONFIG_CANBUS_FREQUENCY=1000000
CONFIG_CANBUS_FILTER=y
CONFIG_INLINE_STEPPER_HACK=y
CONFIG_INITIAL_PINS=""
EOF

echo ">>> Building EBB36 firmware..."
cd "$KLIPPER_DIR"
make olddefconfig
make clean
make -j$(nproc)

echo ">>> Flashing EBB36 (UUID: $EBB36_UUID)..."
~/klippy-env/bin/python3 ~/katapult/scripts/flash_can.py -i can0 -f "$KLIPPER_DIR/out/klipper.bin" -u "$EBB36_UUID"

# ─── Build & Flash Kraken ────────────────────────────────────────────────────

echo ">>> Configuring firmware for Kraken (STM32H723)..."
cat > "$KLIPPER_DIR/.config" <<'EOF'
CONFIG_LOW_LEVEL_OPTIONS=y
CONFIG_MACH_STM32=y
CONFIG_BOARD_DIRECTORY="stm32"
CONFIG_MCU="stm32h723xx"
CONFIG_CLOCK_FREQ=520000000
CONFIG_FLASH_SIZE=0x40000
CONFIG_FLASH_BOOT_ADDRESS=0x8000000
CONFIG_RAM_START=0x20000000
CONFIG_RAM_SIZE=0x20000
CONFIG_STACK_SIZE=512
CONFIG_FLASH_APPLICATION_ADDRESS=0x8020000
CONFIG_STM32_SELECT=y
CONFIG_MACH_STM32H723=y
CONFIG_MACH_STM32H7=y
CONFIG_HAVE_STM32_USBOTG=y
CONFIG_STM32_USB_DOUBLE_BUFFER_TX=y
CONFIG_HAVE_STM32_FDCANBUS=y
CONFIG_HAVE_STM32_USBCANBUS=y
CONFIG_STM32_DFU_ROM_ADDRESS=0x1ff09800
CONFIG_STM32_FLASH_START_20000=y
CONFIG_STM32_CLOCK_REF_25M=y
CONFIG_CLOCK_REF_FREQ=25000000
CONFIG_STM32F0_TRIM=16
CONFIG_STM32_USBCANBUS_PA11_PA12=y
CONFIG_STM32_CMENU_CANBUS_PD0_PD1=y
CONFIG_STM32_CANBUS_PD0_PD1=y
CONFIG_USBCANBUS=y
CONFIG_USB=y
CONFIG_USB_VENDOR_ID=0x1d50
CONFIG_USB_DEVICE_ID=0x614e
CONFIG_USB_SERIAL_NUMBER_CHIPID=y
CONFIG_USB_SERIAL_NUMBER="12345"
CONFIG_CANBUS=y
CONFIG_CANBUS_FREQUENCY=1000000
CONFIG_INITIAL_PINS=""
CONFIG_INLINE_STEPPER_HACK=y
EOF

echo ">>> Building Kraken firmware..."
cd "$KLIPPER_DIR"
make olddefconfig
make clean
make -j$(nproc)

echo ">>> Flashing Kraken (UUID: $KRAKEN_UUID)..."
~/klippy-env/bin/python3 ~/katapult/scripts/flash_can.py -i can0 -f "$KLIPPER_DIR/out/klipper.bin" -u "$KRAKEN_UUID"

# ─── Done ────────────────────────────────────────────────────────────────────

echo ">>> Starting Klipper..."
systemctl start klipper.service

echo ">>> All CAN devices updated successfully."
